version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        - PORT=${SERVER_PORT:-3000}
    image: siosa/node
    working_dir: /app
    volumes:
      - ./:/app:cached
      - ./node_modules:/app/node_modules:delegated
    depends_on:
      - 'postgresql'
    ports:
      - ${SERVER_PORT:-3000}:3000
    command: ['yarn', 'dev']
  postgresql:
    image: postgres:12.1-alpine
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./docker/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgresql:
