export default [
  'Animate Weapon',
  'Arctic Armour',
  'Artillery Ballista',
  'Barrage',
  'Bear Trap',
  'Blade Flurry',
  'Blade Vortex',
  'Bladefall',
  'Blast Rain',
  'Blink Arrow',
  'Blood Rage',
  'Burning Arrow',
  'Caustic Arrow',
  'Charged Dash',
  'Cobra Lash',
  'Cremation',
  'Cyclone',
  'Dash',
  'Desecrate',
  'Detonate Dead',
  'Double Strike',
  'Dual Strike',
  'Elemental Hit',
  'Ensnaring Arrow',
  'Ethereal Knives',
  'Explosive Arrow',
  'Explosive Trap',
  'Fire Trap',
  'Flamethrower Trap',
  'Flicker Strike',
  'Frenzy',
  'Frost Blades',
  'Galvanic Arrow',
  'Grace',
  'Haste',
  'Hatred',
  'Herald of Agony',
  'Herald of Ice',
  'Ice Shot',
  'Ice Trap',
  'Lacerate',
  'Lancing Steel',
  'Lightning Arrow',
  'Lightning Strike',
  'Mirror Arrow',
  'Pestilent Strike',
  'Phase Run',
  'Plague Bearer',
  "Poacher's Mark",
  'Precision',
  'Projectile Weakness',
  'Puncture',
  'Purity of Ice',
  'Rain of Arrows',
  'Reave',
  'Riposte',
  'Scourge Arrow',
  'Seismic Trap',
  'Shattering Steel',
  'Shrapnel Ballista',
  'Siege Ballista',
  'Smoke Mine',
  'Spectral Shield Throw',
  'Spectral Throw',
  'Split Arrow',
  'Summon Ice Golem',
  'Temporal Chains',
  'Tornado Shot',
  'Toxic Rain',
  'Unearth',
  'Venom Gyre',
  'Viper Strike',
  'Volatile Dead',
  'Whirling Blades',
  'Wild Strike',
  'Withering Step',
  'Abyssal Cry',
  'Ancestral Protector',
  'Ancestral Warchief',
  'Anger',
  'Animate Guardian',
  'Berserk',
  'Bladestorm',
  'Blood and Sand',
  'Chain Hook',
  'Cleave',
  'Consecrated Path',
  'Decoy Totem',
  'Determination',
  'Devouring Totem',
  'Dominating Blow',
  'Dread Banner',
  'Earthquake',
  'Enduring Cry',
  'Flesh and Stone',
  'Glacial Hammer',
  'Ground Slam',
  'Heavy Strike',
  'Herald of Ash',
  'Herald of Purity',
  'Holy Flame Totem',
  'Ice Crash',
  'Immortal Call',
  'Infernal Blow',
  'Leap Slam',
  'Molten Shell',
  'Molten Strike',
  'Perforate',
  'Pride',
  'Punishment',
  'Purity of Fire',
  'Rallying Cry',
  'Reckoning',
  'Rejuvenation Totem',
  'Searing Bond',
  'Shield Charge',
  'Shockwave Totem',
  'Smite',
  'Static Strike',
  'Steelskin',
  'Summon Flame Golem',
  'Summon Stone Golem',
  'Sunder',
  'Sweep',
  'Tectonic Slam',
  'Vengeance',
  'Vigilant Strike',
  'Vitality',
  'Vulnerability',
  'War Banner',
  "Warlord's Mark",
  'Arc',
  'Arctic Breath',
  'Armageddon Brand',
  "Assassin's Mark",
  'Ball Lightning',
  'Bane',
  'Blight',
  'Bodyswap',
  'Bone Offering',
  'Brand Recall',
  'Clarity',
  'Cold Snap',
  'Conductivity',
  'Contagion',
  'Conversion Trap',
  'Convocation',
  'Dark Pact',
  'Despair',
  'Discharge',
  'Discipline',
  'Divine Ire',
  'Elemental Weakness',
  'Enfeeble',
  'Essence Drain',
  'Fireball',
  'Firestorm',
  'Flame Dash',
  'Flame Surge',
  'Flameblast',
  'Flammability',
  'Flesh Offering',
  'Freezing Pulse',
  'Frost Bomb',
  'Frost Wall',
  'Frostbite',
  'Frostblink',
  'Frostbolt',
  'Glacial Cascade',
  'Herald of Thunder',
  'Ice Nova',
  'Ice Spear',
  'Icicle Mine',
  'Incinerate',
  'Kinetic Blast',
  'Lightning Spire Trap',
  'Lightning Tendrils',
  'Lightning Trap',
  'Lightning Warp',
  'Magma Orb',
  'Malevolence',
  'Orb of Storms',
  'Power Siphon',
  'Purifying Flame',
  'Purity of Elements',
  'Purity of Lightning',
  'Pyroclast Mine',
  'Raise Spectre',
  'Raise Zombie',
  'Righteous Fire',
  'Scorching Ray',
  'Shock Nova',
  'Siphoning Trap',
  'Soulrend',
  'Spark',
  'Spirit Offering',
  'Storm Brand',
  'Storm Burst',
  'Storm Call',
  'Stormblast Mine',
  'Summon Carrion Golem',
  'Summon Chaos Golem',
  'Summon Holy Relic',
  'Summon Lightning Golem',
  'Summon Raging Spirit',
  'Summon Skeletons',
  'Summon Skitterbots',
  'Tempest Shield',
  'Vortex',
  'Wave of Conviction',
  'Winter Orb',
  'Wither',
  'Wrath',
  'Zealotry',
  'Detonate Mines',
  'Portal',
]
